<?php
// // Connect to the PostgreSQL database
// $conn = pg_connect("host=localhost port=5432 dbname=mydatabase user=myusername password=mypassword");

// if (!$conn) {
//   die("Connection failed: " . pg_last_error());
// }

// // Select all blog posts from the database
// $sql = "SELECT * FROM posts";
// $result = pg_query($conn, $sql);

// // Display each blog post as a list item in an iframe on the feed page
// while ($row = pg_fetch_assoc($result)) {
//   echo "<iframe src='feed.html' frameborder='0'></iframe>";
// }

// // Close the connection to the database
// pg_close($conn);
?>

<head>
  <link rel="stylesheet" href="/assets/css/blog.css" />
</head>

<section class="profile-summary">
  <!-- Generated by fetching data to the database -->
  Author data and whatnot
  <h2> Authored by ${authorName}</h2>
  <p> About the author: ${authorBioAndWhatNot}</p>
</section>

<!-- Blog related content -->
<section class="blog-container">
  <div class="title-container">
    <div class="title-image">
      <img id="title-image-src" src="" alt="blog post image" />
    </div>
    <div class="title-details">
      <div class="title-description">
        <div class="title-name">Blogpost's title </div>
        <div class="title-textarea"> Blogpost's description </div>
      </div>
      <div class="social-container">
        <div class="social-item">
          <img class="social-svg" src="/assets/images/heart-add.svg" />
          <div class="social-text"><b>K</b></div>
        </div>

        <div class="social-item">
          <img class="social-svg" src="/assets/images/comment.svg" />
          <div class="social-text">
            <b>K</b>
          </div>
        </div>

        <div class="social-item">
          <img class="social-svg" src="/assets/images/reblog.svg" />
          <div class="social-text">
            <b>K</b>
          </div>
        </div>

        <div class="social-item">
          <img class="social-svg" src="/assets/images/edit.svg" />
          <div class="social-text">
            <b>K</b>
          </div>
        </div>

        <div class="social-item">
          <img class="social-svg" src="/assets/images/bookmark.svg" />
          <div class="social-text">
            <b>K</b>
          </div>
        </div>

        <div class="social-item">
          <img class="social-svg" src="/assets/images/delete.svg" />
          <div class="social-text">
            <b>K</b>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="content-container">
 <p>Numquam quisquam ut adipisci modi etincidunt. Aliquam neque tempora eius etincidunt. Numquam quiquia dolor dolorem voluptatem numquam. Sit consectetur aliquam magnam voluptatem sit velit adipisci. Sit eius neque dolor. Quiquia amet neque quiquia sit adipisci. Amet dolorem tempora dolor ipsum modi.</p>
  </div>

  <div class="comment-container">
    <form action="#">
      <label for="comment-name">Comment:</label>
      <div><textarea class="comment-textarea"></textarea></div>
      <button type="submit">Submit</button>
    </form>
  </div>
</section>